In [31]:
#Import numpy library
import numpy as np

In [38]:
#Create random 5x5 ndarray
X = np.random.rand(5, 5)

In [41]:
#Normalize the array 
Xmean = X.mean() 
Xstd = X.std()
X_normalized = (X - Xmean) / Xstd

In [43]:
#Save the result of the normalized array
np.save('X_normalized.npy', X_normalized)

In [44]:
#print output
print(X_normalized)

[[-1.25263603  0.36248292  0.52790671 -0.84847037  1.35483351]
 [ 0.06434724  0.80765654 -0.96440346 -0.81899636 -1.41210386]
 [ 1.60249731 -1.8644137  -0.28014398  0.00892605  0.80106712]
 [-0.03114045  1.64106916 -0.22422073 -0.85829909  1.59049526]
 [ 1.07361319  0.7950821  -0.96151876 -0.79092653 -0.3227038 ]]


In [45]:
#Get the first positive integers from 1 - 100
A = np.arange(1,101) 
#Then construct a 10x10 array, then get the squares of each integers
Aarray = A.reshape(10,10) ** 2 

In [29]:
#Find elements divisible by 3
divisible = A[A % 3 == 0]

In [30]:
#Save to file
np.save("div_by_3.npy", divisible)

In [22]:
#print output
print(divisible)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
