In [22]:
#Import numpy library
import numpy as np

In [24]:
#Create random 5x5 ndarray
X = np.random.rand(5, 5)

In [38]:
#Normalize X
Xmean = X.mean() 
Xstd = X.std()
Xnormalized = (X - Xmean) / Xstd

In [39]:
#Save the result of the normalized array
np.save('X_normalized.npy', Xnormalized)

In [40]:
#print output
print(Xnormalized)

[[-1.59565069 -1.1540401   0.0545932   1.27538413 -0.04314275]
 [-0.6169413  -0.36033139  0.42454355  0.23849779  2.1047331 ]
 [ 0.78885753  1.58186781 -1.62738335 -0.59505226 -0.17121451]
 [-1.24321837 -0.03050061 -1.52992266 -0.04343387  1.9837278 ]
 [ 0.34309834  0.17492267  0.23813022 -0.33115436  0.13363008]]


In [41]:
#Import numpy library
import numpy as np

In [47]:
#Get the first positive integers from 1 - 100
A = np.arange(1,101) 
#Then construct a 10x10 array, then get the squares of each integers
Aarray = A.reshape(10,10) ** 2 

In [48]:
#Find elements divisible by 3
divisible = A[A % 3 == 0]

In [49]:
#Save to file
np.save("div_by_3.npy", divisible)

In [50]:
#print output
print(divisible)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
